export const Constants = {
    PRODUCT_LIST: "PRODUCT_LIST",
    PRODUCT_LIST_REDUCER: 'PRODUCT_LIST_REDUCER',
    PRODUCT_LIST_DEL: 'PRODUCT_LIST_DEL',
    PRODUCT_DELETE_REQUEST: 'PRODUCT_DELETE_REQUEST',
    PRODUCT_DELETE_SUCCESS: 'PRODUCT_DELETE_SUCCESS',
    SHOW_PRODUCT_LIST: 'SHOW_PRODUCT_LIST',
    SHOW_PRODUCTS: 'SHOW_PRODUCTS',
    GET_UPSELL_ACTION: 'GET_UPSELL_ACTION',
    GET_UPSELL_REDUCER: 'GET_UPSELL_REDUCER',

    ACCEPT_OFFER_LIST: 'ACCEPT_OFFER_LIST',
    ACCEPT_OFFER_LIST_REDUCER: 'ACCEPT_OFFER_LIST_REDUCER',
    ACCPET_UPSELL: 'ACCPET_UPSELL',
    ACCPET_UPSELL_LIST: 'ACCPET_UPSELL_LIST',

    DECLINE_OFFER_LIST: 'DECLINE_OFFER_LIST',
    DECLINE_OFFER_LIST_REDUCER: 'DECLINE_OFFER_LIST_REDUCER', 
    DECLINE_UPSELL: 'DECLINE_UPSELL',
    DECLINE_UPSELL_LIST: 'DECLINE_UPSELL_LIST',

    SHOW_PRODUCT_LISTING: 'SHOW_PRODUCT_LISTING',
    SHOW_PRODUCT_LIST_REDUCER: 'SHOW_PRODUCT_LIST_REDUCER',
    SHOW_PRODUCT_DELETE: 'SHOW_PRODUCT_DELETE',
    SHOW_PRO_DELETE: 'SHOW_PRO_DELETE', 

    TRIGGER_PRODUCT_LISTING: 'TRIGGER_PRODUCT_LISTING',
    TRIGGER_PRODUCT_REDUCER: 'TRIGGER_PRODUCT_REDUCER',

    EDIT_MAIN_PRO_REQUEST: 'EDIT_MAIN_PRO_REQUEST',
    EDIT_MAIN_PRO_SUCCESS: 'EDIT_MAIN_PRO_SUCCESS',
    EDIT_UPSELL_MAIN_REQUEST: 'EDIT_UPSELL_MAIN_REQUEST',
    EDIT_UPSELL_MAIN_SUCCESS: 'EDIT_UPSELL_MAIN_SUCCESS',

    EDIT_ACCEPT_PRO_REQUEST: 'EDIT_ACCEPT_PRO_REQUEST',
    EDIT_ACCEPT_PRO_SUCCESS: 'EDIT_ACCEPT_PRO_SUCCESS',
    EDIT_UPSELL_ACCEPT_REQUEST: 'EDIT_UPSELL_ACCEPT_REQUEST',
    EDIT_UPSELL_ACCEPT_SUCCESS: 'EDIT_UPSELL_ACCEPT_SUCCESS',
    
    EDIT_DECLINE_PRO_REQUEST: 'EDIT_DECLINE_PRO_REQUEST',
    EDIT_DECLINE_PRO_SUCCESS: 'EDIT_DECLINE_PRO_SUCCESS',
    EDIT_UPSELL_DECLINE_REQUEST: 'EDIT_UPSELL_DECLINE_REQUEST',
    EDIT_UPSELL_DECLINE_SUCCESS: 'EDIT_UPSELL_DECLINE_SUCCESS',

    MAIN_DELETE_REQUEST: 'MAIN_DELETE_REQUEST',
    MAIN_DELETE_SUCCESS: 'MAIN_DELETE_REQUEST',
    MAIN_DELETE_ERROR: 'MAIN_DELETE_REQUEST'
}